apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysinfo-wa-deployment
spec:
  replicas: 6  # Number of desired replicas
  selector:
    matchLabels:
      app: sysinfo-wa
  template:
    metadata:
      labels:
        app: sysinfo-wa
    spec:
      containers:
      - name: sysinfo-wa
        image: yash5090/sysinfo-wa:latest
        ports:
        - containerPort: 3000
